version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "15.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "false"
      LIST_DB: "true"
      DB_MAXCONN: "${DB_MAXCONN-100}"
      WORKERS: "${WORKERS-0}"
      MAX_CRON_THREADS: "${MAX_CRON_THREADS-0}"
      LIMIT_MEMORY_HARD: "${LIMIT_MEMORY_HARD-2684354560}"
      LIMIT_MEMORY_SOFT: "${LIMIT_MEMORY_SOFT-2147483648}"
      SERVER_WIDE_MODULES: "${SERVER_WIDE_MODULES-base,web}"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:14-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: docker.io/mailhog/mailhog
